#Builded for run 0.9.0 from _templates/.travis.yml

language: python
python:
  - '3.3'
install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - coverage run --source=run setup.py test
after_success:
  - coveralls
notifications:
  email:
    - roll@respect31.com
#deploy:
#  provider: pypi
#  user: roll
#  password:
#    secure: JaTeiyjnimmtwhbdfPMZZdtp+5S920vb0HobJWL1QQjHVAo5Hwt0kTWYG+zjDrpWUL+NanVNqhQA8xnvWKbI5cZ+n3PvS7KFbgn6XcTYfeEGyEdYUFi0sXaUsgcfke+9nyMBDLoRH2M7TGqpLY2dmXk5C0h0RMkkAPjxgZCan94=