# Block: caution
#TO MAKE CHANGES USE "meta" DIRECTORY (see packgram docs).

# Block: language
language: 
  python

# Block: python
python:
  - '3.3'
  - '3.4'

# Block: install
install:
  - pip install coveralls
  - pip install sugarbowl clyde dialog>=0.4 find>=0.3 render>=0.3 claire>=0.7 nose coverage

# Block: script
script:
  - coverage run --source=run setup.py test

# Block: after_success
after_success:
  - coveralls

# Block: notifications
notifications:
  email:
    - roll@respect31.com

# Block: deploy
deploy:
  provider: pypi
  user: roll
  password:
    secure: JaTeiyjnimmtwhbdfPMZZdtp+5S920vb0HobJWL1QQjHVAo5Hwt0kTWYG+zjDrpWUL+NanVNqhQA8xnvWKbI5cZ+n3PvS7KFbgn6XcTYfeEGyEdYUFi0sXaUsgcfke+9nyMBDLoRH2M7TGqpLY2dmXk5C0h0RMkkAPjxgZCan94=
  on:
    tags: true
    all_branches: true
