#TO MAKE CHANGES USE "meta" DIRECTORY (see packgram docs).

language: 
  python

python:
  - '3.3'
  - '3.4'

install:
  - pip install coveralls
  - pip install box>=0.42 color>=0.2 clyde>=0.2 dialog>=0.4 find>=0.3 render>=0.2 nose coverage

script:
  - coverage run --source=run setup.py test

after_success:
  - coveralls

notifications:
  email:
    - roll@respect31.com

deploy:
  provider: pypi
  user: roll
  password:
    secure: JaTeiyjnimmtwhbdfPMZZdtp+5S920vb0HobJWL1QQjHVAo5Hwt0kTWYG+zjDrpWUL+NanVNqhQA8xnvWKbI5cZ+n3PvS7KFbgn6XcTYfeEGyEdYUFi0sXaUsgcfke+9nyMBDLoRH2M7TGqpLY2dmXk5C0h0RMkkAPjxgZCan94=
  on:
    tags: true
    all_branches: true
