language: python
python:
  - '3.3'
install:
  - pip install coveralls
script:
  - coverage run --source=run setup.py test
after_success:
  - coveralls
notifications:
  email:
    - roll@respect31.com
deploy:
  provider: pypi
  user: roll
  password:
    secure: bnPlFu7/xweFXqkhnQgDS4v3b9777u/x8kXhQlcK/VxijJGGN6+qqxE1vRM1D3nQblB2/Ydgqzdz9sBQvx6rf2xZXczJ06+zYDAY9J8d2dsokS47v/8oLU/pFDxqm8qTRKIQn5Bnl4A22InIA82F39/KDWqE6LKDvmSfcNsjv1Q=